"""
AURA Mars — Illustrative 3D Mission Scene

Renders a deterministic, illustrative Plotly 3D terrain scene with
landing/rover/target/hazard/uncertainty markers and two candidate
routes. This is NOT a digital elevation model and NOT real mission
navigation data — it exists purely to communicate the shape of a
future "mission console" concept during a presentation.

Everything here is generated by a fixed mathematical function (no
randomness, no external data), so the scene renders identically on
every run.
"""

from typing import Optional

import numpy as np
import plotly.graph_objects as go
import streamlit as st

ILLUSTRATIVE_DISCLAIMER = (
    "Illustrative terrain visualization — not real mission navigation data. "
    "Uses a synthetic surface, not a Mars digital elevation model."
)

_MARS_TERRAIN_COLORSCALE = [
    [0.0, "#2A160D"],
    [0.25, "#5A2E17"],
    [0.5, "#8C4A28"],
    [0.75, "#C07A46"],
    [1.0, "#E8B48C"],
]


def _generate_terrain(grid_size: int = 60) -> tuple:
    """
    Generate a deterministic synthetic terrain height field.

    Uses a fixed combination of sinusoids over a regular grid — no
    randomness, no real elevation data. Purely for illustrative shape.
    """
    x = np.linspace(-10, 10, grid_size)
    y = np.linspace(-10, 10, grid_size)
    xx, yy = np.meshgrid(x, y)

    zz = (
        1.4 * np.sin(xx * 0.35) * np.cos(yy * 0.28)
        + 0.6 * np.cos((xx + yy) * 0.5)
        + 0.35 * np.sin(xx * 0.9)
        - 0.02 * (xx ** 2 + yy ** 2)
    )
    return xx, yy, zz


def create_mars_scene() -> go.Figure:
    """
    Build the illustrative 3D Mars terrain scene.

    Returns
    -------
    go.Figure
        A Plotly figure with a synthetic terrain surface, mission markers
        (landing zone, rover, science target, hazards, uncertainty zones),
        and two candidate routes (A and B).
    """
    xx, yy, zz = _generate_terrain()

    fig = go.Figure()

    # --- Terrain surface ---
    fig.add_trace(go.Surface(
        x=xx, y=yy, z=zz,
        colorscale=_MARS_TERRAIN_COLORSCALE,
        showscale=False,
        opacity=0.95,
        lighting=dict(ambient=0.55, diffuse=0.6, roughness=0.9, specular=0.05),
        contours={"z": {"show": False}},
        hoverinfo="skip",
        name="Terrain",
    ))

    def _z_at(x_val: float, y_val: float) -> float:
        """Sample the same deterministic height function at a point."""
        return (
            1.4 * np.sin(x_val * 0.35) * np.cos(y_val * 0.28)
            + 0.6 * np.cos((x_val + y_val) * 0.5)
            + 0.35 * np.sin(x_val * 0.9)
            - 0.02 * (x_val ** 2 + y_val ** 2)
        ) + 0.25  # small lift so markers sit above the surface

    # --- Fixed illustrative points ---
    landing_zone = (-7.0, -6.0)
    rover_pos = (-6.2, -5.3)
    science_target = (5.5, 4.0)
    hazards = [(1.0, -2.0), (-2.0, 3.0), (3.5, 6.5)]
    uncertainty_zones = [(6.5, -3.0), (-4.0, -6.5)]

    def marker(pos, label, color, symbol, size=6):
        x0, y0 = pos
        fig.add_trace(go.Scatter3d(
            x=[x0], y=[y0], z=[_z_at(x0, y0)],
            mode="markers+text",
            marker=dict(size=size, color=color, symbol=symbol, line=dict(color="#090B10", width=1)),
            text=[label],
            textposition="top center",
            textfont=dict(size=11, color="#E9EEF5"),
            hovertext=[label],
            hoverinfo="text",
            name=label,
        ))

    marker(landing_zone, "Landing Zone", "#62D49B", "diamond", size=8)
    marker(rover_pos, "Rover", "#D9683A", "circle", size=7)
    marker(science_target, "Science Target", "#55B8D9", "diamond", size=8)

    for i, h in enumerate(hazards, 1):
        marker(h, f"Hazard {i}", "#E8AD56", "x", size=6)

    for i, u in enumerate(uncertainty_zones, 1):
        marker(u, f"Uncertainty {i}", "#A98BFF", "circle-open", size=9)

    # --- Routes ---
    def route_line(points, label, color, dash="solid"):
        xs = [p[0] for p in points]
        ys = [p[1] for p in points]
        zs = [_z_at(px, py) + 0.1 for px, py in points]
        fig.add_trace(go.Scatter3d(
            x=xs, y=ys, z=zs,
            mode="lines",
            line=dict(color=color, width=6, dash=dash),
            name=label,
            hoverinfo="name",
        ))

    route_a = [rover_pos, (-3.0, -1.0), (1.0, 1.5), science_target]
    route_b = [rover_pos, (-5.0, -2.5), (-2.5, 1.0), (1.5, 4.5), science_target]

    route_line(route_a, "Route A (direct, higher risk)", "#929CAA", dash="dot")
    route_line(route_b, "Route B (evidence-supported)", "#D9683A", dash="solid")

    fig.update_layout(
        scene=dict(
            xaxis=dict(visible=False),
            yaxis=dict(visible=False),
            zaxis=dict(visible=False),
            bgcolor="#090B10",
            camera=dict(eye=dict(x=1.35, y=-1.35, z=0.9)),
        ),
        paper_bgcolor="#090B10",
        plot_bgcolor="#090B10",
        margin=dict(l=0, r=0, t=10, b=0),
        height=520,
        legend=dict(
            font=dict(color="#E9EEF5", size=11),
            bgcolor="rgba(18, 23, 34, 0.75)",
            bordercolor="#2B3748",
            borderwidth=1,
        ),
        showlegend=True,
    )

    return fig


def render_mission_scene(
    container: Optional["st.delta_generator.DeltaGenerator"] = None,
    key: str = "mission_scene",
) -> None:
    """
    Render the illustrative 3D Mars scene into Streamlit, with the
    required disclaimer shown directly above it.

    Parameters
    ----------
    key : str
        Streamlit element key for the chart. Pass a distinct value if
        this is ever rendered more than once in the same script run.
    """
    target = container or st
    target.caption(ILLUSTRATIVE_DISCLAIMER)
    fig = create_mars_scene()
    target.plotly_chart(fig, width="stretch", key=key)
