"""
AURA Mars — Report Export Component

Provides a download button that exports the current pipeline result
as a structured Markdown report.
"""

import io
from datetime import datetime

import streamlit as st

from src.models import PipelineResult
from src.utils import format_confidence_display


def render_export_button(result: PipelineResult):
    """
    Render a download button for exporting a PipelineResult as Markdown.

    Parameters
    ----------
    result : PipelineResult
        The pipeline result to export.
    """
    if result is None:
        return

    # Build report content
    lines = [
        "# AURA Mars — Research Report",
        f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
        "",
        "---",
        "",
        "## Question",
        result.question,
        "",
        "## Mission Relevance",
        ", ".join(result.mission_areas) if result.mission_areas else "General Mars Research",
        "",
        "## Claim",
        result.claim,
        "",
        "## Sources",
    ]
    for src in result.sources:
        lines.append(f"- {src}")

    lines.extend([
        "",
        "## Evidence Strength",
        f"- **Final Score**: {format_confidence_display(result.confidence.final_confidence)}",
        f"- **Confidence Level**: {result.confidence.label}",
        f"- **Evidence Confidence**: {format_confidence_display(result.confidence.evidence_confidence)}",
        f"- **Generation Consistency**: {format_confidence_display(result.confidence.generation_consistency)}",
        "",
        "### Sub-Scores",
        f"- Source Agreement: {format_confidence_display(result.confidence.source_agreement)}",
        f"- Retrieval Match Strength: {format_confidence_display(result.confidence.retrieval_match_strength)}",
        f"- Source Count Score: {format_confidence_display(result.confidence.source_count_score)}",
        f"- Source Quality Score: {format_confidence_display(result.confidence.source_quality_score)}",
        "",
        "*This is an evidence-strength indicator based on retrieved source quality, agreement, "
        "relevance, and answer consistency. It is not a statistical probability that the answer is true.*",
    ])

    if result.score_explanation:
        lines.extend([
            "",
            "### Score Explanation",
            result.score_explanation,
        ])

    if result.evidence_summary:
        lines.extend(["", "## Evidence Summary", result.evidence_summary])

    lines.extend([
        "",
        "## Known",
        result.known if result.known else "No directly supported facts were isolated for this question.",
        "",
        "## Unknown / Not Covered",
        result.unknowns if result.unknowns else "All aspects appear to be addressed.",
        "",
        "## Conflicting",
        result.conflicting if result.conflicting else "No conflicts identified in the retrieved passages.",
        "",
        "## Limitations",
        result.limitations if result.limitations else "No specific limitations were called out for this question.",
    ])

    if result.mission_relevance_text:
        lines.extend(["", "## Why This Matters for Mars Missions", result.mission_relevance_text])

    lines.extend([
        "",
        "## Verification",
        f"**Status**: {'All claims verified' if result.verification.verified else 'Some claims unverified'}",
    ])

    if result.verification.unsupported_claims:
        lines.append("")
        lines.append("**Unsupported claims**:")
        for claim in result.verification.unsupported_claims:
            lines.append(f"- {claim}")

    if result.follow_up_questions:
        lines.append("")
        lines.append("## Suggested Follow-Up Questions")
        for fq in result.follow_up_questions:
            lines.append(f"- {fq}")

    lines.extend([
        "",
        "---",
        "*Report generated by AURA Mars — Augmented Understanding & Research Assistant for Mars Exploration*",
    ])

    report_text = "\n".join(lines)

    # Render download button
    st.download_button(
        label="Download Report (.md)",
        data=report_text.encode("utf-8"),
        file_name=f"aura_mars_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md",
        mime="text/markdown",
        key="export_report_btn",
    )
