"""
AURA Mars — Shared Utilities

Helper functions used across multiple modules.
"""

import numpy as np
from typing import List
import ollama
from src.config import OLLAMA_HOST

_ollama_client = None

def get_ollama_client() -> ollama.Client:
    """Get or create a cached Ollama client instance for efficiency."""
    global _ollama_client
    if _ollama_client is None:
        _ollama_client = ollama.Client(host=OLLAMA_HOST)
    return _ollama_client



def cosine_similarity(vec_a: List[float], vec_b: List[float]) -> float:
    """
    Compute cosine similarity between two vectors.

    Returns a float in [-1.0, 1.0]. Returns 0.0 if either vector
    has zero magnitude (avoids division by zero).
    """
    a = np.array(vec_a)
    b = np.array(vec_b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    if norm_a == 0.0 or norm_b == 0.0:
        return 0.0
    return float(np.dot(a, b) / (norm_a * norm_b))


def normalize_score(value: float, min_val: float = 0.0, max_val: float = 1.0) -> float:
    """
    Clamp and normalise a value to [0.0, 1.0] given its expected range.

    If min_val == max_val, returns 0.0 to avoid division by zero.
    """
    if max_val == min_val:
        return 0.0
    clamped = max(min_val, min(value, max_val))
    return (clamped - min_val) / (max_val - min_val)


def format_confidence_display(score: float) -> str:
    """
    Format a 0.0–1.0 confidence score as a human-readable percentage string.

    Example: 0.723 → "72.3%"
    """
    return f"{score * 100:.1f}%"


def export_report(pipeline_result, path: str) -> None:
    """
    Export a PipelineResult to a structured Markdown report file.

    Parameters
    ----------
    pipeline_result : PipelineResult
        The result object from the pipeline.
    path : str
        Output file path (should end in .md).
    """
    lines = [
        "# AURA Mars — Research Report",
        "",
        f"## Question",
        f"{pipeline_result.question}",
        "",
        f"## Claim",
        f"{pipeline_result.claim}",
        "",
        f"## Sources",
    ]
    for src in pipeline_result.sources:
        lines.append(f"- {src}")
    lines.extend([
        "",
        f"## Confidence",
        f"**Score**: {format_confidence_display(pipeline_result.confidence.final_confidence)}",
        f"**Label**: {pipeline_result.confidence.label}",
        f"**Explanation**: {pipeline_result.score_explanation}",
        "",
        f"## Unknowns / Not Covered",
        f"{pipeline_result.unknowns}",
        "",
        f"## Verification",
        f"**Verified**: {'Yes' if pipeline_result.verification.verified else 'No'}",
    ])
    if pipeline_result.verification.unsupported_claims:
        lines.append("**Unsupported claims**:")
        for claim in pipeline_result.verification.unsupported_claims:
            lines.append(f"- {claim}")
    lines.extend([
        "",
        "---",
        "*Report generated by AURA Mars*",
    ])

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
